### PR TITLE
Added the Custom Metrics

### PR DESCRIPTION
**Pull request by emreds**
## Describe your changes
We needed to add custom metrics for the fitness landscape analysis.

## What is the related task number?
3-1

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.

### CODE REVIEW

**Comment by Stargazer1998** [comment]
I am not sure if the input array will be 1D, we may need to deal with higher dimensional arrays. In the case of mean and variance taking the last epoch's values into account would make sense in such a situation.

**Comment by emreds** [comment]
> I am not sure if the input array will be 1D, we may need to deal with higher dimensional arrays. In the case of mean and variance taking the last epoch's values into account would make sense in such a situation.

This can also handle the multidimensional arrays, like `[[1,2], [2,3]]` but we should agree on what the output will be.

**Comment by emreds** [comment]
I will add them as a test case for demonstration @Stargazer1998.

**Review by Stargazer1998 — APPROVED** [review]
Everything seems to be correct

**Pull request merged**
